import os
import re
import json
import uuid
from typing import Dict, Any, List
from datetime import datetime

# --- PDF Dependency Integration (Mirroring ZAP Parser) ---
# It's assumed pdf_extractor.py exists and works as intended.
try:
    from .pdf_extractor import extract_text_from_pdf
except ImportError:
    try:
        from pdf_extractor import extract_text_from_pdf
    except ImportError:
        print("Error: pdf_extractor.py not found. Please ensure it is in the same directory.")
        def extract_text_from_pdf(pdf_path: str) -> str:
            raise NotImplementedError("pdf_extractor.py not found.")
# --- End PDF Dependency Integration ---


# --- Core Nmap Parsing Function (REVISED) ---
def parse_nmap_report(raw_nmap_text: str) -> Dict[str, Any]:
    """
    Parses raw Nmap report text (from a custom report format) into a structured dictionary.
    """
    raw_nmap_text = re.sub(r'\r\n|\r', '\n', raw_nmap_text)

    # --- GLOBAL CLEANUP ---
    # 1. Remove standard page markers
    raw_nmap_text = re.sub(r'\n\s*Page \d+ of \d+\s*', '\n', raw_nmap_text, flags=re.DOTALL)
    # 2. Remove the specific footer text
    raw_nmap_text = re.sub(r'\n\s*Generated by NetShieldAI Reporting Engine\s*', '\n', raw_nmap_text, flags=re.DOTALL)

    report: Dict[str, Any] = {
        "scan_metadata": {
            "tool": "Nmap Scanner",
            "report_id": str(uuid.uuid4()),
            "target_ip": None,
            "scan_date": None,
            "host_status": None,
            "scan_arguments": None
        },
        "summary": {
            "ports_found": 0,
            "open_ports_count": 0
        },
        "open_ports": []
    }

    ## 1. Metadata and Summary Extraction

    # Target IP
    ip_match = re.search(r"TARGET IP:\s*([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})", raw_nmap_text)
    if ip_match:
        ip_str = ip_match.group(1).split('SCAN DATE:')[0].strip()
        report["scan_metadata"]["target_ip"] = ip_str

    # Scan Date
    date_match = re.search(r"SCAN DATE:\s*(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})", raw_nmap_text)
    if date_match:
        date_str = date_match.group(1).strip()
        try:
            report["scan_metadata"]["scan_date"] = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S").isoformat()
        except ValueError:
            report["scan_metadata"]["scan_date"] = date_str

    # Host Status
    status_match = re.search(r"HOST STATUS:\s*(\w+)", raw_nmap_text)
    if status_match:
        report["scan_metadata"]["host_status"] = status_match.group(1).strip()

    # Scan Arguments
    args_match = re.search(
        r"Scan\s*Arguments\s*(.*?)\n(?:Open Ports|\Z)",
        raw_nmap_text,
        re.DOTALL
    )
    if args_match:
        args_raw = args_match.group(1).strip()
        # Replaced clean_text_block call with inline logic for internal whitespace compression
        cleaned_args = re.sub(r'\s+', ' ', args_raw).strip()
        report["scan_metadata"]["scan_arguments"] = cleaned_args.replace('\\', '') 

    # Ports Found count
    ports_found_match = re.search(r"Open Ports\s*Found\s*(\d+)", raw_nmap_text)
    if ports_found_match:
        count = int(ports_found_match.group(1))
        report["summary"]["ports_found"] = count
        report["summary"]["open_ports_count"] = count
    
    ## 2. Detailed Port Findings Extraction
    port_blocks_start = raw_nmap_text.find("Detected Open Ports & Services")
    port_blocks_text = raw_nmap_text[port_blocks_start:] if port_blocks_start != -1 else raw_nmap_text

    # FINAL, ROBUST Pattern: Service Version block is now OPTIONAL
    port_pattern = re.compile(
        # Group 1: Port line
        r"Port\s*(?P<port_info>\d+\s*/\s*tcp\s*[^\n]+)\n"
        # Group 2: State line
        r"State:\s*(?P<state>[^\s]+)\s*\|\s*Protocol:\s*tcp\s*\n"
        
        # --- FIX: Make Service Version Block Optional ---
        r"(?:" # Start non-capturing optional group
            r"Service Version:(?:\n\s*)*?" # Match "Service Version:" 
            r"(?P<service_version>.*?)\n"  # Capture the content
        r")?" # End optional group
        
        # Group 4: Mandatory Local Process block
        r"Local Process Detected:(?:\n\s*)*?(?P<local_process>.*?)"
        
        # SIMPLE BOUNDARY: Looks ahead for the start of the next "Port" or the absolute end of string.
        r"(?=\n\s*Port|\Z)", 
        re.DOTALL | re.IGNORECASE
    )

    ports: List[Dict[str, Any]] = []

    for match in port_pattern.finditer(port_blocks_text):
        data = match.groupdict()

        port_info_parts = data['port_info'].split('/')
        port_num = int(port_info_parts[0].strip()) if port_info_parts[0].strip().isdigit() else None
        
        # Extract service name (e.g., "MSRPC" from "tcp MSRPC")
        service_name = port_info_parts[1].strip() if len(port_info_parts) > 1 else "Unknown"
        service_name = service_name.split(' ', 1)[1].strip() if ' ' in service_name else service_name

        # Clean Service Version 
        # Check if the service_version group was captured (it will be None if optional group failed to match)
        service_version_raw = data.get('service_version', '') or ''
        service_version = re.sub(r'\s+', ' ', service_version_raw).strip()
        
        if not service_version:
            service_version = service_name # Use service_name as fallback

        # Clean Local Process
        local_process = re.sub(r'\s+', ' ', data['local_process']).strip()
        
        ports.append({
            "port": port_num,
            "protocol": "tcp",
            "state": data['state'].strip(),
            "service_name": service_name,
            "service_version": service_version,
            "local_process": local_process,
        })

    report["open_ports"] = ports
    report["summary"]["open_ports_count"] = len(ports)
    return report

# ----------------------------------------------------------------------
## Nmap Wrapper Function (Now mirrors process_zap_report_file)
# ----------------------------------------------------------------------

# NOTE: The read_file_content_safely function has been removed, 
# as process_nmap_report_file now calls extract_text_from_pdf directly.

def process_nmap_report_file(file_path: str) -> Dict[str, Any]:
    """
    Handles file I/O for an Nmap report (assumed to be from a PDF report output): 
    checks existence, extracts raw text using the PDF extractor,
    calls the parser, and adds file system metadata.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Nmap report not found: {file_path}")
    print(f"Processing Nmap report: {file_path}")
    try:
        # --- CALLING THE PDF EXTRACTOR (Mirroring ZAP) ---
        raw_text = extract_text_from_pdf(file_path) 
        if not raw_text.strip():
            raise ValueError("Extracted text from file is empty.")
            
        report_data = parse_nmap_report(raw_text)
        
        report_data["file_metadata"] = {
            "filename": os.path.basename(file_path),
            "file_size": os.path.getsize(file_path),
            "last_modified": datetime.fromtimestamp(os.path.getmtime(file_path)).isoformat()
        }
        return report_data
        
    except Exception as e:
        print(f"Error processing Nmap report {file_path}: {e}")
        # Re-raise the exception to allow the calling app to handle the failure
        raise

if __name__ == "__main__":
    # --- Mock Setup for Demonstration (Changed to raw string to silence SyntaxWarning) ---
    sample_nmap_report_text = r"""
Network Assessment Report
Nmap Scanner
TARGET IP:
192.168.29.48SCAN DATE:
2025-11-28 20:40:56HOST STATUS:
Up
Scan Summary
Metric Details
Scan
Argumentsnmap --exclude-ports 5000 -A -T4 -oG D:\\NetShieldAI\
\Services\\results\\network_scanner\
\scan_result_aggressive.txt 192.168.29.48
Open Ports
Found3
Detected Open Ports & Services
Port 135 / tcp MSRPC
State:  Open  |  Protocol:  tcp  
Service Version:
                           Microsoft Windows RPC
Local Process Detected:
                           svchost.exe
Page 1 of 2
Port 139 / tcp NETBIOS-SSN
State:  Open  |  Protocol:  tcp  
Service Version:
                           Microsoft Windows netbios-ssn
Local Process Detected:
                           System
Port 445 / tcp MICROSOFT-DS?
State:  Open  |  Protocol:  tcp  
Local Process Detected:
                           System
Generated by NetShieldAI Reporting Engine
Page 2 of 2
"""
    # NOTE: The __main__ block is intentionally left simple as this module relies on the 
    # external 'pdf_extractor.py' module being present at runtime for full testing.
    sample_pdf_path = r"D:\NetShieldAI_Chatbot\Data\reports\nmap_report.pdf"
    try:
        nmap_report = process_nmap_report_file(sample_pdf_path)
        print(json.dumps(nmap_report, indent=2))
    except NotImplementedError:
        print("Please ensure 'pdf_extractor.py' is implemented to run the file processing.")
    except Exception as e:
        print(f"Failed to process Nmap report: {e}")